# Generated by Django 3.1 on 2020-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('dated_created', models.DateField(auto_now_add=True, choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivery', 'Delivery')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('dated_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
