# Generated by Django 3.1 on 2020-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dated_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivery', 'Delivery')], max_length=200),
        ),
    ]
